apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-syspawn-com
  namespace: cert-manager
spec:
  secretName: staging-syspawn-com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.staging.syspawn.com"
  dnsNames:
  - "staging.syspawn.com"
  - "*.staging.syspawn.com"
