apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: syspawn-com
  namespace: cert-manager
spec:
  secretName: syspawn-com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.syspawn.com"
  dnsNames:
  - "syspawn.com"
  - "*.syspawn.com"
