apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-database
  namespace: nextcloud
spec:
  storageClassName: "truenas-nfs-csi"
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
