apiVersion: v1
kind: Secret
metadata: 
  name: keycloak-database
  namespace: keycloak
data: 
  username: postgres
  password: <password>
---
apiVersion: v1
kind: Secret
metadata: 
  name: keycloak
  namespace: keycloak
data: 
  username: admin
  password: <password>
