apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall
  namespace: heimdall     
spec:
  storageClassName: "truenas-nfs-csi" 
  accessModes:
    - ReadWriteMany         
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi          
