apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-syspawn-com
  namespace: cert-manager
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "traefik"
spec:
  secretName: local-syspawn-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.syspawn.com"
  dnsNames:
  - "local.syspawn.com"
  - "*.local.syspawn.com"
