apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-syspawn-com
  namespace: cert-manager
spec:
  secretName: local-syspawn-com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.syspawn.com"
  dnsNames:
  - "local.syspawn.com"
  - "*.local.syspawn.com"
