apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: syspawn-com
  namespace: cert-manager
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "traefik"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "traefik"
  secretName: syspawn-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.syspawn.com"
  dnsNames:
  - "syspawn.com"
  - "*.syspawn.com"
