driver: freenas-api-nfs
instance_id:
httpConnection:
  protocol: http
  host: 10.0.0.8
  port: 80
  username: root
  apiKey: <api-key>
  allowInsecure: true
zfs:
  datasetParentName: tank/kubernetes/...
  detachedSnapshotsDatasetParentName: tank/kubernetes/...
  datasetEnableQuotas: true
  datasetEnableReservation: false
  datasetPermissionsMode: "0777"
  datasetPermissionsUser: 0
  datasetPermissionsGroup: 0
nfs:
  shareHost: 10.0.0.8
  shareAlldirs: false
  shareAllowedHosts: []
  shareAllowedNetworks: []
  shareMaprootUser: root
  shareMaprootGroup: root
  shareMapallUser: ""
  shareMapallGroup: ""
